list: $/yamobile/blog/models/post/columns.yaml
modelClass: Yamobile\Blog\Models\Post
title: Post
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'yamobile/blog/post/update/:id'
